# baseURL = "http://kfirbreger.com/"
languageCode = "en-us"
title = "Kfir Breger"
theme = "kfirbreger"


[params]
    author = "Kfir Breger"
    info = "Developer, Photographer, Mountain Fan"
    description = "Kfir's home on the web"
    keywords = "developer,blog,personal,sport"
    lastChange = 2018

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 10
    url = "https://github.com/kfirbreger/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 20
    url = "https://instagram.com/kfirbreger"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 100
    url = "https://www.linkedin.com/in/kfir-breger"

# Menu links
[[menu.main]]
    name = "About"
    weight = 10
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "Photos"
    weight = 3
    url = "/photos/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "micro"
    weight = 4
    url ="/micro"

